* git difme

#+BEGIN_SRC bash
git clone git://git.ricketyspace.net/git-difme.git
#+END_SRC

stages files and makes commits on a list of git repositories based on
some rules.

** rules

the rules specify what type of files to stage and commit.

file types:

   - modified file (M).
   - deleted file (D).
   - untracked file (?).

the rules are defined per git repository in the config file.

if git-difme finds finds already staged files, it'll commit them first
before doing anything.

** config

the config file must be at =~/.config/git-difme/config=.

the config is simply a scheme file that defines =difme-repos=
function:

#+BEGIN_SRC scheme
(define (difme-repos)
  (list '("/path/to/git/repo/foo" "M" "D" "?")
        '("/path/to/git/repo/bar" "M")
        '("/path/to/git/repo/baz" "M" "?")
        '("/path/to/git/repo/frb")))
#+END_SRC

- for repo ~foo~, git difm will only stage and commit modified (M),
  deleted (D) and untracked (?) files.
- for repo ~bar~, git difm will only stage and commit modified (M)
  files.
- for repo ~baz~, git difm will only stage and commit modified (M) and
  untracked (?) files.
- for repo ~frb~, git difm will only stage and commit all types of
  files.

#+END_SRC

** license

gnu general public license version 3 or higher.
